[build]
  command = "cd frontend && npm install && npm run build && pwsh -Command \"Copy-Item -Recurse -Force ./dist/* ../dist/\""
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
