[build]
  command = "cd frontend && npm install && npm run build && cp -r dist/* ../dist/ && cp dist/index.html ../index.html"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
